/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.Dimension;
import java.awt.Toolkit;
import modelo.Variables;
import static modelo.Variables.frmCambiaPin;
import static modelo.Variables.frmConEstado;
import static modelo.Variables.frmConPremios;
import static modelo.Variables.frmConTkt;
import static modelo.Variables.frmLiqDia;
import static modelo.Variables.frmTktsEmi;
import static modelo.Variables.frmVtaTkts;

/**
 *
 * @author Administrador
 */
public class Inicio extends javax.swing.JFrame {

    Login frmLogin;

    public Inicio() {
        initComponents();
        configuraUI();

        if (Variables.mIDUSU == null) {
            frmLogin = new Login(this);
            frmLogin.setLocationRelativeTo(null);
            frmLogin.setVisible(true);
        }

        //this.barraInferior.setText("Usuario:");
    }

    private void configuraUI() {

        setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/img/lucky48.jpg")));
        setVisible(true);
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEscritorio = new javax.swing.JDesktopPane();
        panelPrincipal = new javax.swing.JPanel();
        barraInferior = new javax.swing.JLabel();
        MenuPrincipal = new javax.swing.JMenuBar();
        mAdministrador = new javax.swing.JMenu();
        mMantenimiento = new javax.swing.JMenu();
        mMan_Sorteos = new javax.swing.JMenuItem();
        mMan_Sucursales = new javax.swing.JMenuItem();
        mMan_Usuarios = new javax.swing.JMenuItem();
        mAdm_CierreSor = new javax.swing.JMenuItem();
        mMovimientos = new javax.swing.JMenu();
        mMov_Suc = new javax.swing.JMenuItem();
        mMov_Usu = new javax.swing.JMenuItem();
        mAdm_reportes = new javax.swing.JMenu();
        mVentas = new javax.swing.JMenu();
        mVenta_tkts = new javax.swing.JMenuItem();
        mVentas_tktsEmitidos = new javax.swing.JMenuItem();
        mVentas_liqDia = new javax.swing.JMenuItem();
        mVentas_tktsPremiados = new javax.swing.JMenuItem();
        mVentas_EstadoCta = new javax.swing.JMenuItem();
        mSistema = new javax.swing.JMenu();
        mSis_cambioUsu = new javax.swing.JMenuItem();
        mSis_cambioPin = new javax.swing.JMenuItem();
        mSis_config = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lotto Banca");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        panelPrincipal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelPrincipalKeyPressed(evt);
            }
        });

        barraInferior.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        barraInferior.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barraInferior.setText("DERECHOS RESERVADOS -- SECCAB SOFTWARE");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraInferior, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(0, 262, Short.MAX_VALUE)
                .addComponent(barraInferior))
        );

        panelEscritorio.setLayer(panelPrincipal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelEscritorioLayout = new javax.swing.GroupLayout(panelEscritorio);
        panelEscritorio.setLayout(panelEscritorioLayout);
        panelEscritorioLayout.setHorizontalGroup(
            panelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelEscritorioLayout.setVerticalGroup(
            panelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(panelEscritorio, java.awt.BorderLayout.CENTER);

        mAdministrador.setText("Modulo Administrador");

        mMantenimiento.setText("Mantenimiento");

        mMan_Sorteos.setText("Sorteos");
        mMantenimiento.add(mMan_Sorteos);

        mMan_Sucursales.setText("Sucursales");
        mMantenimiento.add(mMan_Sucursales);

        mMan_Usuarios.setText("Usuarios");
        mMantenimiento.add(mMan_Usuarios);

        mAdministrador.add(mMantenimiento);

        mAdm_CierreSor.setText("Cierre Sorteos");
        mAdministrador.add(mAdm_CierreSor);

        mMovimientos.setText("Movimientos");

        mMov_Suc.setText("Sucursales");
        mMovimientos.add(mMov_Suc);

        mMov_Usu.setText("Usuarios");
        mMovimientos.add(mMov_Usu);

        mAdministrador.add(mMovimientos);

        mAdm_reportes.setText("Reportes y Consultas");
        mAdministrador.add(mAdm_reportes);

        MenuPrincipal.add(mAdministrador);

        mVentas.setText("Modulo Ventas");

        mVenta_tkts.setText("Venta Tiquetes");
        mVenta_tkts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mVenta_tktsActionPerformed(evt);
            }
        });
        mVentas.add(mVenta_tkts);

        mVentas_tktsEmitidos.setText("Tiquetes Emitidos");
        mVentas_tktsEmitidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mVentas_tktsEmitidosActionPerformed(evt);
            }
        });
        mVentas.add(mVentas_tktsEmitidos);

        mVentas_liqDia.setText("Liquidacion Diaria");
        mVentas_liqDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mVentas_liqDiaActionPerformed(evt);
            }
        });
        mVentas.add(mVentas_liqDia);

        mVentas_tktsPremiados.setText("Tiquetes Premiados");
        mVentas_tktsPremiados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mVentas_tktsPremiadosActionPerformed(evt);
            }
        });
        mVentas.add(mVentas_tktsPremiados);

        mVentas_EstadoCta.setText("Estado Cuenta");
        mVentas_EstadoCta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mVentas_EstadoCtaActionPerformed(evt);
            }
        });
        mVentas.add(mVentas_EstadoCta);

        MenuPrincipal.add(mVentas);

        mSistema.setText("Sistema");
        mSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSistemaActionPerformed(evt);
            }
        });

        mSis_cambioUsu.setText("Cambio Usuario");
        mSis_cambioUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSis_cambioUsuActionPerformed(evt);
            }
        });
        mSistema.add(mSis_cambioUsu);

        mSis_cambioPin.setText("Cambio Pin");
        mSis_cambioPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSis_cambioPinActionPerformed(evt);
            }
        });
        mSistema.add(mSis_cambioPin);

        mSis_config.setText("Configuración");
        mSis_config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSis_configActionPerformed(evt);
            }
        });
        mSistema.add(mSis_config);

        MenuPrincipal.add(mSistema);

        setJMenuBar(MenuPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelPrincipalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelPrincipalKeyPressed
        // TODO add your handling code here:


    }//GEN-LAST:event_panelPrincipalKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:


    }//GEN-LAST:event_formKeyPressed

    private void mSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSistemaActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_mSistemaActionPerformed

    private void mSis_cambioUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSis_cambioUsuActionPerformed
        // TODO add your handling code here:
        frmLogin = new Login(this);
        frmLogin.setLocationRelativeTo(null);
        frmLogin.setVisible(true);
    }//GEN-LAST:event_mSis_cambioUsuActionPerformed

    private void mVenta_tktsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mVenta_tktsActionPerformed
        // TODO add your handling code here:

        if (frmVtaTkts == null) {
            frmVtaTkts = new VentaTkts();
            Dimension ds = this.panelEscritorio.getSize();
            Dimension fs = frmVtaTkts.getSize();
            frmVtaTkts.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            this.panelEscritorio.add(frmVtaTkts);
            frmVtaTkts.show();
        } else {
            frmVtaTkts.toFront();
            frmVtaTkts.restoreSubcomponentFocus();
        }

    }//GEN-LAST:event_mVenta_tktsActionPerformed

    private void mVentas_tktsEmitidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mVentas_tktsEmitidosActionPerformed

        if (frmTktsEmi == null) {
            frmTktsEmi = new TktsEmitidos();
            Dimension ds = this.panelEscritorio.getSize();
            Dimension fs = frmTktsEmi.getSize();
            frmTktsEmi.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            this.panelEscritorio.add(frmTktsEmi);
            frmTktsEmi.show();
        } else {
            frmTktsEmi.toFront();
            frmTktsEmi.restoreSubcomponentFocus();
        }

    }//GEN-LAST:event_mVentas_tktsEmitidosActionPerformed

    private void mVentas_liqDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mVentas_liqDiaActionPerformed
        // TODO add your handling code here:
        if (frmLiqDia == null) {
            frmLiqDia = new LiqDiaria();
            Dimension ds = this.panelEscritorio.getSize();
            Dimension fs = frmLiqDia.getSize();
            frmLiqDia.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            this.panelEscritorio.add(frmLiqDia);
            frmLiqDia.show();
        } else {
            frmLiqDia.toFront();
            frmLiqDia.restoreSubcomponentFocus();
        }

    }//GEN-LAST:event_mVentas_liqDiaActionPerformed

    private void mVentas_tktsPremiadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mVentas_tktsPremiadosActionPerformed
        // TODO add your handling code here:
        if (frmConPremios == null) {
            frmConPremios = new ConsultaPremios();
            Dimension ds = this.panelEscritorio.getSize();
            Dimension fs = frmConPremios.getSize();
            frmConPremios.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            this.panelEscritorio.add(frmConPremios);
            frmConPremios.show();
        } else {
            frmConPremios.toFront();
            frmConPremios.restoreSubcomponentFocus();
        }

    }//GEN-LAST:event_mVentas_tktsPremiadosActionPerformed

    private void mVentas_EstadoCtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mVentas_EstadoCtaActionPerformed
        // TODO add your handling code here:
        if (frmConEstado == null) {
            frmConEstado = new ConsultaEstado();
            Dimension ds = this.panelEscritorio.getSize();
            Dimension fs = frmConEstado.getSize();
            frmConEstado.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            this.panelEscritorio.add(frmConEstado);
            frmConEstado.show();
        } else {
            frmConEstado.toFront();
            frmConEstado.restoreSubcomponentFocus();
        }

    }//GEN-LAST:event_mVentas_EstadoCtaActionPerformed

    private void mSis_configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSis_configActionPerformed
        // TODO add your handling code here:

        if (frmConTkt == null) {
            frmConTkt = new ConfiguraTkt();
            Dimension ds = this.panelEscritorio.getSize();
            Dimension fs = frmConTkt.getSize();
            frmConTkt.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            this.panelEscritorio.add(frmConTkt);
            frmConTkt.show();
        } else {
            frmConTkt.toFront();
            frmConTkt.restoreSubcomponentFocus();
        }
    }//GEN-LAST:event_mSis_configActionPerformed

    private void mSis_cambioPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSis_cambioPinActionPerformed
        // TODO add your handling code here:
         if (frmCambiaPin == null) {
            frmCambiaPin = new CambiarPin();
            Dimension ds = this.panelEscritorio.getSize();
            Dimension fs = frmCambiaPin.getSize();
            frmCambiaPin.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            this.panelEscritorio.add(frmCambiaPin);
            frmCambiaPin.show();
        } else {
            frmCambiaPin.toFront();
            frmCambiaPin.restoreSubcomponentFocus();
        }
        
        
    }//GEN-LAST:event_mSis_cambioPinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JLabel barraInferior;
    public static javax.swing.JMenuItem mAdm_CierreSor;
    public static javax.swing.JMenu mAdm_reportes;
    public static javax.swing.JMenu mAdministrador;
    public static javax.swing.JMenuItem mMan_Sorteos;
    public static javax.swing.JMenuItem mMan_Sucursales;
    public static javax.swing.JMenuItem mMan_Usuarios;
    public static javax.swing.JMenu mMantenimiento;
    public static javax.swing.JMenuItem mMov_Suc;
    public static javax.swing.JMenuItem mMov_Usu;
    public static javax.swing.JMenu mMovimientos;
    private javax.swing.JMenuItem mSis_cambioPin;
    private javax.swing.JMenuItem mSis_cambioUsu;
    private javax.swing.JMenuItem mSis_config;
    public static javax.swing.JMenu mSistema;
    public static javax.swing.JMenuItem mVenta_tkts;
    public static javax.swing.JMenu mVentas;
    private javax.swing.JMenuItem mVentas_EstadoCta;
    public static javax.swing.JMenuItem mVentas_liqDia;
    public static javax.swing.JMenuItem mVentas_tktsEmitidos;
    private javax.swing.JMenuItem mVentas_tktsPremiados;
    private javax.swing.JDesktopPane panelEscritorio;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables

}
